#!/bin/bash
id=$1

echo "Running backsql mariadb odbc configuration for $id".

eval $($app "$conf" source-get-os-variables $id)

cat > "database_template_$id.ini" << EOF 
[${DB_DATABASE}]
Description=backdb connection
Driver=MariaDB Unicode
SERVER=${DB_SERVER}
USER=${DB_USERNAME}
PASSWORD=${DB_PASSWORD}
DATABASE=${DB_DATABASE}
PORT=${DB_PORT}
EOF

odbcinst -i -s -l -f "database_template_$id.ini"

echo "Done."