# SLF4J logger properties
org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.org.apache.directory=warn
org.slf4j.simpleLogger.log.org.alefzero=debug
org.slf4j.simpleLogger.showThreadName=true
