/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.alefzero.padl;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.concurrent.ScheduledFuture;

import org.alefzero.padl.config.PadlConfigurator;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
	protected static final Logger logger = LogManager.getLogger();

	private static final String DEFAULT_ACTION = "help";
	private static final String DEFAULT_CONFIGURATION_FILENAME = "./conf/padl.yaml";

	public static void main(String[] args) {
		logger.info("Padl is starting");
		logger.debug("Padl is starting with parameters %s", Arrays.toString(args));

		String action = args.length > 0 ? args[0] : DEFAULT_ACTION;
		String configurationFilename = getConfigurationFilename(args);
		new App().startAction(action, configurationFilename);
	}

	private ScheduledFuture<?> executor = null;

	private void startAction(String action, String configurationFilename) {
		logger.trace(".startAction [action: {}, configurationFilename: {}]", action, configurationFilename);
		try {
			Path configurationFile = Paths.get(configurationFilename);
			switch (action.toLowerCase()) {
			case "admin-config":
				getAdminConfiguration(configurationFile);
				break;
			case "run":
				runSyncProcess(configurationFile);
				break;
			case "help":
			default:
				this.help();
				break;
			}
			System.exit(0);
		} catch (IOException e) {
			logger.error("Error processing action {}: ", action.toLowerCase(), e);
			e.printStackTrace();
			System.exit(1);
		}
	}

	public static String getConfigurationFilename(String[] args) {
		logger.trace(".getConfigurationFilename [args: {}]", Arrays.toString(args));
		String configurationFilename = args.length > 1 ? args[1] : "";
		configurationFilename = configurationFilename.isEmpty() ? DEFAULT_CONFIGURATION_FILENAME
				: configurationFilename;
		logger.trace(".getConfigurationFilename [return: {}]", configurationFilename);
		return configurationFilename;
	}

	private void getAdminConfiguration(Path configurationFile) throws IOException {
		PadlConfigurator config = new PadlConfigurator(configurationFile);
		System.out.println(config.getTargetAdminConfig());
	}

	private void help() {
		logger.trace(".help");
		logger.info("""


				Padl - an easy proxy ldap configurator.
				Usage: run.sh admin-config|help|run

				""");
		
		System.out.println("""


				Padl - an easy proxy ldap configurator.
				Usage: run.sh admin-config|help|run

				""");
	}

	private void runSyncProcess(Path configurationFile) {
		logger.trace(".runSyncProcess [configurationFilename: {}]", configurationFile);

		Thread shutdownListener = new Thread() {
			public void run() {
				logger.info("Requesting padl processes to stop (10s)...");
				try {
					if (executor != null) {
						executor.cancel(false);
						Thread.sleep(10000);
					}
					logger.info("Padl is shutdown.");
				} catch (InterruptedException e) {
					logger.error("Aborting...");
				}
			}
		};

		Runtime.getRuntime().addShutdownHook(shutdownListener);
		// Thread.sleep(20);
		logger.info("Padl is done.");

	}
}
