#!/bin/bash

echo "Running backsql mariadb odbc configuration".

eval $($app "$conf" source-get-os-variables sql)

cat > database_template.ini << EOF 
[backdb]
Description=backdb connection
Driver=MariaDB Unicode
SERVER=${DB_SERVER}
USER=${DB_USERNAME}
PASSWORD=${DB_PASSWORD}
DATABASE=${DB_DATABASE}
PORT=${DB_PORT}
EOF

odbcinst -i -s -l -f database_template.ini

echo "Done."